#!/usr/bin/env bash
#
# Author:
#   mmtrt [Taqi Raza]
#
# Description:
#   download and prepare notepad3 for snap
#
# Date: Feb 12 2018
#

dlnp3 () {
    wget --accept "*.zip" --content-disposition --trust-server-names "https://www.rizonesoft.com/download/3943/" &> /dev/null
    for fnts in andalemo.ttf arialbd.ttf arialbi.ttf ariali.ttf arial.ttf ariblk.ttf comicbd.ttf comic.ttf courbd.ttf courbi.ttf couri.ttf cour.ttf georgiab.ttf georgiai.ttf georgia.ttf georgiaz.ttf impact.ttf l_10646.ttf lucon.ttf micross.ttf symbol.ttf tahomabd.ttf tahoma.ttf timesbd.ttf timesbi.ttf timesi.ttf times.ttf trebucbd.ttf trebucbi.ttf trebucit.ttf trebuc.ttf verdanab.ttf verdanai.ttf verdana.ttf verdanaz.ttf webdings.ttf wingding.ttf
    do
    wget https://github.com/caarlos0-graveyard/msfonts/blob/master/fonts/$fnts?raw=true -P share/wine/fonts &> /dev/null
    mv share/wine/fonts/$fnts?raw=true share/wine/fonts/$fnts
    done
}

mknp3 () {
    ver="$(wget https://www.rizonesoft.com/downloads/notepad3 -q -S -O - 2>&1 | grep '<td>3.' | sed 's|<td>||;s|</td>||')"
    7z x Notepad3_${ver}.zip &> /dev/null
    7z x Notepad3_${ver}_x86.zip -x'!Changes.txt' -x'!License.txt' -x'!Readme.txt' -x'!Notepad3.ini' -x'!client.wyc' -x'!wyUpdate.exe' -o"usr/share/notepad3" &> /dev/null
    mv usr/share/notepad3/Notepad3.exe usr/share/notepad3/notepad3.exe
    find "usr" -type d -execdir chmod 755 {} +
    mkdir -p usr/share/pixmaps && mkdir -p usr/share/applications && mkdir bin
    wrestool -x -t3 -n9 usr/share/notepad3/notepad3.exe --raw > usr/share/pixmaps/notepad3.png
}

mkdsk () {
cat > notepad3.desktop <<'EOF1'
[Desktop Entry]
Name=Notepad3
GenericName=Text Editor
Comment=Simple and free source code editor.
Encoding=UTF-8
Version=
Type=Application
Terminal=false
Icon=${SNAP}/usr/share/pixmaps/notepad3.png
Exec=notepad3 %F
StartupWMClass=notepad3.exe
Categories=Utility;TextEditor
MimeType=text/plain;text/css;text/html;text/x-c++hdr;text/x-c++src;text/x-chdr;text/x-java;text/x-makefile;text/x-python;text/x-sh
EOF1
sed -i -e 's|Version=|Version='"$ver"'|g' notepad3.desktop
}

dlnp3
mknp3
mkdsk
mv notepad3 bin && mv notepad3.desktop usr/share/applications
rm Notepad3*.zip dl_np3