#!/usr/bin/env bash
#
# Author:
#   mmtrt [Taqi Raza]
#
# Description:
#   download and prepare notepad3 for snap
#
# Date: Feb 12 2018
#

dlnp3 () {
    ver="$(wget https://www.rizonesoft.com/downloads/notepad3 -q -S -O - 2>&1 | grep 'Notepad3_' | sed '1d;3,7d;s|Notepad3_||g;s|.zip||g' | awk '{print $1}' | head -n1)"
    wget --accept "*.zip" "https://github.com/rizonesoft/Notepad3/releases/download/RELEASE_${ver}/Notepad3_${ver}.zip" &> /dev/null
}

mknp3 () {
    mkdir -p usr/share && mkdir wine-platform
    7z x Notepad3_${ver}.zip &> /dev/null
    7z x Notepad3_${ver}_x86.zip -x'!Changes.txt' -x'!License.txt' -x'!Readme.txt' -o"usr/share/notepad3" &> /dev/null
    mv usr/share/notepad3/Notepad3.exe usr/share/notepad3/notepad3.exe
    find "usr" -type d -execdir chmod 755 {} +
    mkdir -p usr/share/pixmaps && mkdir -p usr/share/applications && mkdir bin
    wrestool -x -t3 -n1 usr/share/notepad3/notepad3.exe --raw > usr/share/pixmaps/notepad3.png
}

mkdsk () {
cat > notepad3.desktop <<'EOF1'
[Desktop Entry]
Name=Notepad3
GenericName=Text Editor
Comment=Simple and free source code editor.
Encoding=UTF-8
Version=
Type=Application
Terminal=false
Icon=${SNAP}/usr/share/pixmaps/notepad3.png
Exec=notepad3 %F
StartupWMClass=notepad3.exe
Categories=Utility;TextEditor
MimeType=text/plain;text/css;text/html;text/x-c++hdr;text/x-c++src;text/x-chdr;text/x-java;text/x-makefile;text/x-python;text/x-sh;application/x-wine-extension-ini;application/x-wine-extension-inf;
EOF1
sed -i -e 's|Version=|Version='"$ver"'|g' notepad3.desktop
}

dlnp3
mknp3
mkdsk
mv notepad3 bin && mv notepad3.desktop usr/share/applications && cp -R -p {bin,usr,wine-platform} $SNAPCRAFT_PART_INSTALL