#!/usr/bin/env bash
#
# Author:
#   mmtrt [Taqi Raza]
#
# Description:
#   notepad3 wrapper for snap
#
# Date: Feb 12 2018
#

ARCH="i386-linux-gnu"

export WINEVERPATH=$SNAP
export PATH=$SNAP/bin:$SNAP/usr:bin:$PATH 
export WINESERVER=$SNAP/bin/wineserver
export WINELOADER=$SNAP/bin/wine
export winepath=$SNAP/bin/winepath
export WINEDLLPATH=$SNAP/lib/wine/fakedlls
export WINEPREFIX=$SNAP_USER_COMMON/.wine
export WINEDLLOVERRIDES="mscoree,mshtml="
export WINEDEBUG=-all
export LD_LIBRARY_PATH="$SNAP/lib:$SNAP/lib/$ARCH:$SNAP/usr/lib:$SNAP/usr/lib/$ARCH:$LD_LIBRARY_PATH"

export HOME=$SNAP_USER_COMMON
export XDG_DATA_HOME=$SNAP_USER_COMMON/usr/share

# notepad3 env
progName=notepad3
progRealPath=$SNAP/usr/share/$progName
progHome=$SNAP_USER_DATA/$progName
progBin=$progName.exe
progIni=$progHome/notepad3.ini

if [ ! -d $progHome ];then
mkdir -p $progHome
fi

# Delete broken symlinks
find -L "$progHome" -type l -delete &> /dev/null
# Update existing symlinks, add new symlinks
cp -urs "$progRealPath/"* "$progHome" &> /dev/null

if [ ! -d $WINEPREFIX ]; then
mkdir -p $WINEPREFIX/drive_c/windows/Fonts
find /usr/share/fonts/ -type f -name "*.ttf" -exec ln -vs "{}" $WINEPREFIX/drive_c/windows/Fonts/ \; &> /dev/null
cat > $progIni <<'EOF'
[Notepad3]
[Settings]
SaveSettings=1
SaveRecentFiles=1
PathNameFormat=1
;Favorites=.\Favorites\
Favorites=
TabsAsSpaces=0
TabWidth=4
MarkLongLines=1
LongLinesLimit=80
LongLineMode=1
LoadASCIIasUTF8=0
FixLineEndings=0
ToolbarButtons=1 2 4 3 0 5 6 0 7 8 9 0 10 11 0 12 0 24 0 22 23 0 13 14 0 15 0 25 0 17
[Settings2]
;AutoReloadTimeout=2000
;DateTimeLong=
;DateTimeShort=
;DefaultDirectory=
;DefaultExtension=txt
;DenyVirtualSpaceAccess=0
;filebrowser.exe=minipath.exe
;FileCheckInverval=2000
;FileDlgFilters=
;FileLoadWarningMB=1
;MarkOccurrencesMaxCount=2000
;MultiFileArg=0
;NoCGIGuess=0
;NoFadeHidden=0
;NoFileVariables=0
;NoHTMLGuess=0
;PortableMyDocs=1
;OpacityLevel=75
;RelativeFileMRU=1
;ReuseWindow=0
;SciDirectWriteTech=0
;SciFontQuality=3
;SimpleIndentGuides=0
SingleFileInstance=1
ShellAppUserModelID=Notepad3
ShellUseSystemMRU=1
;StickyWindowPosition=0
;TimeStamp=\\$Date:[^\\$]+\\$ | $Date: %Y/%m/%d %H:%M:%S $
;UseOldStyleBraceMatching=0
WebTemplate1=https://google.com/search?q=%s
WebTemplate2=https://en.wikipedia.org/w/index.php?search=%s
;ExtendedWhiteSpaceChars=:
;UpdateDelayHyperlinkStyling=100
;UpdateDelayMarkAllCoccurrences=50
;CurrentLineVerticalSlop=5
[Toolbar Images]
BitmapDefault=Toolbar.bmp
BitmapHot=ToolbarHot.bmp
BitmapDisabled=ToolbarDisabled.bmp
[Toolbar Labels]
;01=New
;02=Open
;03=metapath
;04=Save
;05=Undo
;06=Redo
;07=Cut
;08=Copy
;09=Paste
;10=Find
;11=Replace
;12=Word Wrap
;13=Zoom In
;14=Zoom Out
;15=Scheme
;16=Config
;17=Exit
;18=Save As
;19=Save Copy
;20=Copy All
;21=Clear
;22=Print
;23=Favorites
;24=Add
[Custom Colors]
[Styles]
Use2ndDefaultStyle=0
[Default Text]
[2nd Default Text]
[ANSI Art]
[Apache Config Files]
[Assembly Script]
[AutoHotkey Script]
[AutoIt3 Script]
[AviSynth Script]
[Awk Script]
[Batch Files]
[C# Source Code]
[C/C++ Source Code]
[Cmake Script]
[Coffeescript]
[Configuration Files]
[CSS Style Sheets]
[D Source Code]
[Diff Files]
[Go Source Code]
[Inno Setup Script]
[Java Source Code]
[JavaScript]
[JSON]
[LaTeX Files]
[Lua Script]
[Makefiles]
[Markdown]
[MATLAB]
[Nim Source Code]
[NSIS Script]
[Pascal Source Code]
[Perl Script]
[PowerShell Script]
[Python Script]
[Registry Files]
[Resource Script]
[Ruby Script]
[Shell Script]
[SQL Query]
[Tcl Script]
[VBScript]
[VHDL]
[Visual Basic]
[Web Source Code]
[XML Document]
[YAML]
[Suppressed Messages]
[Window]
[Recent Files]
[Recent Find]
[Recent Replace]
EOF
fi

# Switches: use -something instead of /something to avoid confusion with Unix paths
# Also convert Unix paths to Windows paths.
declare -a args

for arg; do
    if [[ "${arg:0:1}" = "-" ]]; then
        args+=("${arg/#-//}")
    else
        args+=("$($winepath -w "$arg")")
    fi
done

if [ -z "$1" ] ; then
  wine "$progHome/$progBin"
else
  wine start /unix "$progHome/$progBin" "${args[@]}"
fi
