name: notepad3
title: Notepad3 (WINE)
summary: notepad3 is a fast and light-weight text editor.
description: |
 notepad3 is a fast and light-weight Scintilla-based text editor with syntax highlighting. It has a small memory footprint, but is powerful enough to handle most programming jobs.
adopt-info: notepad3

confinement: strict
grade: stable
architectures:
  - build-on: amd64
base: core22
compression: lzo

plugs:
  gtk-3-themes:
    interface: content
    target: $SNAP/share/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/share/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/share/sounds
    default-provider: gtk-common-themes
  desktop:
    mount-host-font-cache: false
  shmem:
    interface: shared-memory
    private: true
  wine-runtime-c22:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime-core22
  wine-7-devel-c22:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-7-devel-core22

environment:
  LD_LIBRARY_PATH: $SNAP/wine-runtime/usr/lib/i386-linux-gnu:$SNAP/wine-runtime/lib/i386-linux-gnu:$SNAP/wine-runtime/usr/lib/x86_64-linux-gnu:$SNAP/wine-runtime/lib/x86_64-linux-gnu${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
  WINEDLLOVERRIDES: "mscoree,mshtml=" # Prevent pop-ups about Wine Mono and Wine Gecko
  RUN_EXE: "$SNAP_USER_DATA/notepad3/notepad3.exe"
  SOMMELIER_KEEP_CWD: "1" # Don't change the working directory so relative paths still work
  NO_AT_BRIDGE: "1" # Fix yad error Failed to connect to socket /tmp/dbus-xxx: No such file or directory
  DISABLE_WAYLAND: "1" # Fix gtk decoration under wayland session
  #LIBGL_DEBUG: verbose
  TMPDIR: $XDG_RUNTIME_DIR

apps:
  notepad3:
    command-chain: [bin/desktop-launch]
    command: bin/sommelier run-exe
    plugs:
      - shmem
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - gsettings
      - opengl
      - home
      - network
      - hardware-observe
      - process-control
      - cups-control
      - removable-media
    desktop: usr/share/applications/notepad3.desktop
  # The wine command can be used to run applications inside the wine
  # environment that this snap uses.
  #
  # For example, users can configure the wine environment of this snap
  # by running `myapp.wine winecfg`.
  wine:
    command-chain: [bin/desktop-launch]
    command: bin/sommelier
    plugs:
      - shmem
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - gsettings
      - opengl
      - home
      - network
      - hardware-observe
      - process-control
      - cups-control
      - removable-media
  # The winetricks command can be used to run winetricks inside the wine
  # environment that this snap uses.
  winetricks:
    command-chain: [bin/desktop-launch]
    command: bin/sommelier winetricks
    plugs:
      - network

parts:
  notepad3:
    plugin: nil
    source: ./snap/local/src
    override-build: |
      craftctl default
      set -ex
      #ver=$(wget https://www.rizonesoft.com/downloads/notepad3 -q -S -O - 2>&1 | grep 'Notepad3_' | sed '1d;3,7d;s|_| |g' | awk '{print $2}' | head -n1)
      snapcraftctl set-version "5.21.905.1"
      ./dl_np3
    stage:
      - bin
      - usr
      - wine-platform
      - wine-runtime
      - sommelier
    build-packages: [wget, unzip]
  # The sommelier script helps you snap Windows applications using Wine. It
  # initializes and configures Wine and installs the Windows application.
  sommelier:
    plugin: make
    source: https://github.com/mmtrt/sommelier-core.git
    source-branch: "new-core22"

  #fix-up-font:
    #plugin: nil
    #after: [gnome/sdk]
    #override-prime: |
      #sed -i '/snap-package/,+1d' $SNAPCRAFT_PRIME/snap/command-chain/desktop-launch

  #fix-bindtext:
    #plugin: nil
    #after: [gnome/sdk]
    #override-prime: |
      #sed -i "$(grep -in bindtext $SNAPCRAFT_PRIME/snap/command-chain/desktop-launch | cut -d':' -f1 | tail -2 | head -1)d" $SNAPCRAFT_PRIME/snap/command-chain/desktop-launch
      #sed -i "$(grep -in bindtext $SNAPCRAFT_PRIME/snap/command-chain/desktop-launch | cut -d':' -f1 | tail -1)d" $SNAPCRAFT_PRIME/snap/command-chain/desktop-launch
