name: notepad3
version: latest
version-script: cat $SNAPCRAFT_STAGE/version
summary: notepad3 is a fast and light-weight text editor.
description: |
 notepad3 is a fast and light-weight Scintilla-based text editor with syntax highlighting. It has a small memory footprint, but is powerful enough to handle most programming jobs.

confinement: strict
grade: stable
architectures:
  - build-on: amd64
  - build-on: i386
base: core18

plugs:
  wine-platform-plug:
    content: wine-base-stable
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes

apps:
  notepad3:
    command: notepad3
    desktop: usr/share/applications/notepad3.desktop
    plugs: [ wayland, x11, opengl, home, desktop, desktop-legacy, hardware-observe, process-control, cups-control, removable-media, wine-platform-plug ]

parts:
  notepad3:
    plugin: nil
    source: ./src
    override-build: |
      snapcraftctl build
      set -ex
      ver=$(wget https://www.rizonesoft.com/downloads/notepad3 -q -S -O - 2>&1 | grep 'Notepad3_' | sed '1d;3,7d;s|Notepad3_||g;s|.zip||g' | awk '{print $1}' | head -n1)
      echo $ver > $SNAPCRAFT_STAGE/version
      ./dl_np3
    stage:
      - bin
      - usr
      - wine-platform
    build-packages: [wget, unzip]
