name: check

on:
  schedule:
  - cron: "0 * * * *"

jobs:
  new-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repo_token: ${{ secrets.PAT }}
    - name: get-latest-version
      run: |
        VERSION="$(wget 2>/dev/null https://www.rizonesoft.com/downloads/notepad3 -qSO- | grep 'Notepad3_' | sed '1d;3,7d;s|_| |g' | awk '{print $2}' | head -n1)"
        last=$(tail -n1 .build | awk '{print $4}')

        if [ "$last" != "$VERSION" ]; then
          echo "$(date -u --rfc-3339=seconds) Version $VERSION" >> .build
        fi
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Trigger build for new version
        branch: master
        repo_token: ${{ secrets.PAT }}
